### ISSUE TITLE
Can there be a "latest" tag?

### ISSUE THREAD

**Issue by aharpervc** [CircleCI-Public/cimg-rust#83]
Hi, I'm using this image in a CI job, but I'd prefer to always stay with the latest version of the compiler. My understanding with Docker is that the convention is to use a tag called `latest` that is progressively updated as new versions are released. It seems like it'd be useful to have that tag for this image too.

Thoughts?

**Comment by BytesGuy** [comment]
@aharpervc 

Hi, as of right now we have no plans to support a `latest` or `current` tag for the `cimg` docker images.

The main reasons for this are summarised already in an issue post for the Go image (the same applies to all our `cimg` docker images), so I am linking this here:

https://github.com/CircleCI-Public/cimg-go/issues/103#issuecomment-726225831

Although this post is a bit old, our stance on this has not changed at this time.

I hope this explanation helps!

**Comment by aharpervc** [comment]
> I hope this explanation helps!

It helps to explain why it's missing, but it doesn't help me to achieve my objective, which is to use the latest version of the compiler.

Do you have a recommendation for how to solve this problem in CircleCI?

**Comment by felicianotech** [comment]
Hey @aharpervc. What most people do is simply change the version in their CircleCI config as needed. This allows the most determinism and makes debugging MUCH easier for you.

Otherwise, your options are:

1. Use the CircleCI [Rust Orb](https://circleci.com/developer/orbs/orb/circleci/rust) with `cimg/base` or another Debian-based image.
2. Use the Docker Library [Rust image](https://hub.docker.com/_/rust). They use the `latest` tag.
3. Just install it yourself during your pipeline.
